In [1]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim
import torch.utils.data
import torchvision.transforms as transforms
from PIL import Image
import cv2

In [2]:
data = pd.read_csv('../final_data.csv')
#data_train = data.sample(frac=1)
files_train = list(data['filename'])
ids_train = [i for i in range(len(files_train))]
data = None
#data_train = None

class MyDataset(torch.utils.data.Dataset):
    def __init__(self, list_IDs, filenames, tranform):
        self.filenames = filenames
        self.list_IDs = list_IDs
        self.transform = tranform
        
    def __getitem__(self, index):
        ID = self.list_IDs[index]
        #cv_in = cv2.imread('../img/'+self.filenames[ID]+'.jpg',1) # color
        cv_in = cv2.imread('../img/'+self.filenames[ID]+'_trans.jpg',0) # grayscale
        pil_in = Image.fromarray(cv_in)
        X = self.transform(pil_in)
        return X

    def __len__(self):
        return len(self.list_IDs)
    

dataset = MyDataset(ids_train,files_train,transforms.Compose([transforms.Resize((256,256)),transforms.ToTensor(),]))
loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=10,
    num_workers=1,
    shuffle=False
)

In [4]:
# actual color images
mean = 0.
std = 0.
nb_samples = 0.
for data in loader:
    batch_samples = data.size(0)
    data = data.view(batch_samples, data.size(1), -1)
    mean += data.mean(2).sum(0)
    std += data.std(2).sum(0)
    nb_samples += batch_samples

mean /= nb_samples
std /= nb_samples
print(mean)
print(std)

tensor([0.5231, 0.5180, 0.5115])
tensor([0.2014, 0.2018, 0.2100])


In [3]:
# transmission images
mean = 0.
std = 0.
nb_samples = 0.
for data in loader:
    batch_samples = data.size(0)
    data = data.view(batch_samples, data.size(1), -1)
    mean += data.mean(2).sum(0)
    std += data.std(2).sum(0)
    nb_samples += batch_samples

mean /= nb_samples
std /= nb_samples
print(mean)
print(std)

tensor([0.5238])
tensor([0.1931])
